neo4j:
  uri: "bolt://localhost:7687"
  username: "neo4j"
  password: "neo4j"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/twitteo-project

firebase:
  project-id: "project-id"
  private-key-id: "private-key-id"
  private-key: "private-key"
  client-email: "email"
  client-id: "client-id"
  client-x509-cert-url: "cert-url"
